name: simple_asset_picker
description: A Flutter image picker based on the KakaoTalk image picker UI.
repository: https://github.com/leegh519/simple_asset_picker
issue_tracker: https://github.com/leegh519/simple_asset_picker/issues
version: 0.0.6

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  photo_manager: ^2.7.1
  flutter_riverpod: ^2.3.7
  collection: ^1.17.1
  video_player: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
